import type { Prompt } from '../types/prompt';

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(9 + (n % 8), (n * 7) % 60, 0, 0);
  return d.toISOString();
};

/**
 * Seed library used when no backend is connected.
 * TODO(backend): delete once `GET /prompts` returns real data.
 */
export const MOCK_PROMPTS: Prompt[] = [
  {
    id: 'p-01',
    title: 'Senior Code Reviewer',
    description: 'Rigorous PR review with severity levels and concrete diffs.',
    content:
      'You are a staff engineer reviewing a pull request.\n\nReview the code below for: correctness, edge cases, performance, security, readability and test coverage.\n\nFor every issue output:\n- Severity: blocker | major | minor | nit\n- File & line reference\n- Why it matters (one sentence)\n- A concrete suggested diff\n\nEnd with a 3-bullet summary and a ship / do-not-ship verdict.\n\nCODE:\n```\n{{code}}\n```',
    category: 'Coding',
    tags: ['review', 'engineering', 'quality'],
    isFavorite: true,
    isPinned: true,
    displayOrder: 0,
    usageCount: 42,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'p-02',
    title: 'Bug Triage Detective',
    description: 'Turns a vague bug report into a ranked hypothesis list.',
    content:
      'Act as a debugging specialist. Given the stack trace, environment and reproduction steps below, produce:\n1. A ranked list of 5 hypotheses with confidence percentages\n2. The single cheapest experiment to falsify each\n3. The instrumentation/log lines you would add first\n\nDo not guess a fix until the top hypothesis is confirmed.\n\nREPORT:\n{{report}}',
    category: 'Coding',
    tags: ['debugging', 'triage'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 1,
    usageCount: 17,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: 'p-03',
    title: 'Positioning Statement Generator',
    description: 'Sharp category-defining positioning in the Dunford format.',
    content:
      'You are a positioning strategist trained on April Dunford\'s framework.\n\nFor the product described below, produce:\n- Competitive alternatives (what people do today)\n- Unique attributes we have that they lack\n- The value those attributes enable\n- The customers who care most\n- The market category we should frame ourselves in\n\nFinish with one 25-word positioning statement, no adjectives like "innovative" or "seamless".\n\nPRODUCT: {{product}}',
    category: 'Marketing',
    tags: ['positioning', 'strategy', 'b2b'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 2,
    usageCount: 28,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },
  {
    id: 'p-04',
    title: 'Landing Page Hero Rewriter',
    description: 'Five hero variants across different emotional angles.',
    content:
      'Rewrite the hero section below into 5 variants. Each variant must use a different angle: outcome-led, pain-led, contrarian, proof-led, and speed-led.\n\nEach variant returns: headline (max 9 words), subhead (max 22 words), primary CTA (max 3 words).\n\nBan the words: revolutionary, seamless, empower, unlock, game-changing.\n\nCURRENT COPY: {{copy}}',
    category: 'Marketing',
    tags: ['copywriting', 'landing-page', 'cro'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 3,
    usageCount: 11,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 'p-05',
    title: 'Long-Form Article Architect',
    description: 'Outlines a 2,000 word article with a defensible thesis.',
    content:
      'You are a features editor. Build an outline for a 2,000-word article on: {{topic}}\n\nDeliver:\n- A one-sentence thesis that someone could disagree with\n- 5 section headers, each with a 2-sentence intent note\n- The specific evidence, data point or anecdote each section needs\n- 3 counter-arguments to pre-empt\n- A closing line that lands the thesis without summarising\n\nTone: {{tone}}. Audience: {{audience}}.',
    category: 'Content Writing',
    tags: ['outline', 'editorial', 'longform'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 4,
    usageCount: 33,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: 'p-06',
    title: 'Ruthless Editor Pass',
    description: 'Cuts 30% of the words without losing meaning.',
    content:
      'Edit the passage below to be 30% shorter while preserving every idea.\n\nRules:\n- Kill adverbs and hedges ("really", "quite", "I think")\n- Prefer active voice and concrete nouns\n- Vary sentence length; no more than two long sentences in a row\n- Do not add new claims\n\nReturn the edited text, then a short table of the 5 biggest cuts and why.\n\nTEXT:\n{{text}}',
    category: 'Content Writing',
    tags: ['editing', 'concise'],
    isFavorite: false,
    isPinned: true,
    displayOrder: 5,
    usageCount: 51,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(2),
  },
  {
    id: 'p-07',
    title: 'Cold Outreach That Gets Replies',
    description: 'Sub-100-word email built on a real observed trigger.',
    content:
      'Write a cold email under 100 words to {{persona}} at {{company}}.\n\nStructure:\n1. One line proving I researched them (use the trigger: {{trigger}})\n2. One line on the problem they likely have\n3. One line of specific proof we solved it elsewhere\n4. A low-friction ask (15 min, or "want the 2-page teardown?")\n\nNo buzzwords, no "hope this finds you well", no exclamation marks.\nProvide 3 subject lines under 6 words.',
    category: 'Email',
    tags: ['outreach', 'sales', 'cold-email'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 6,
    usageCount: 64,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(8),
  },
  {
    id: 'p-08',
    title: 'Difficult Email Diffuser',
    description: 'Rewrites a heated reply into calm, firm professionalism.',
    content:
      'Rewrite my draft email so it stays firm on the substance but removes all heat.\n\nRules:\n- Lead with the shared goal\n- State the constraint or disagreement plainly, once\n- Offer two paths forward\n- End with a clear next step and owner\n- Never sarcastic, never passive-aggressive\n\nDRAFT:\n{{draft}}',
    category: 'Email',
    tags: ['communication', 'conflict'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 7,
    usageCount: 9,
    createdAt: daysAgo(27),
    updatedAt: daysAgo(27),
  },
  {
    id: 'p-09',
    title: 'Impact-First Resume Bullets',
    description: 'Converts duties into quantified XYZ-format achievements.',
    content:
      'Rewrite each responsibility below as a resume bullet in the format:\n"Accomplished [X] as measured by [Y] by doing [Z]."\n\nRequirements:\n- Start with a strong past-tense verb (no "responsible for")\n- Include a number in at least 70% of bullets; mark invented figures as [ESTIMATE]\n- Max 2 lines each\n- Match keywords from the target job description: {{jd}}\n\nRESPONSIBILITIES:\n{{bullets}}',
    category: 'Resume',
    tags: ['career', 'ats', 'bullets'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 8,
    usageCount: 22,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'p-10',
    title: 'Behavioural Interview Rehearsal',
    description: 'Mock interviewer that scores STAR answers honestly.',
    content:
      'Act as a hiring manager for the role: {{role}}.\n\nAsk me one behavioural question at a time. After each answer:\n- Score it 1-5 on Situation, Task, Action, Result, and Reflection\n- Quote the weakest sentence and rewrite it\n- Ask one follow-up probe a real interviewer would ask\n\nDo not move on until I score 4+. Be honest, not encouraging.',
    category: 'Resume',
    tags: ['interview', 'star', 'practice'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 9,
    usageCount: 14,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
  {
    id: 'p-11',
    title: 'Query Optimiser',
    description: 'Explains the plan, then rewrites for index usage.',
    content:
      'You are a database performance engineer.\n\nGiven the schema, the query and the EXPLAIN output below:\n1. Explain in plain English why the planner chose this path\n2. Identify the single most expensive node and why\n3. Propose an optimised query\n4. Propose index changes with exact DDL, and state the write-cost trade-off\n5. Estimate the expected improvement and how to verify it\n\nSCHEMA: {{schema}}\nQUERY: {{query}}\nEXPLAIN: {{explain}}',
    category: 'SQL',
    tags: ['postgres', 'performance', 'indexes'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 10,
    usageCount: 37,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'p-12',
    title: 'Plain English → SQL',
    description: 'Safe, readable SQL from a natural-language question.',
    content:
      'Convert the question into a single SQL query for this schema.\n\nRules:\n- Use CTEs over nested subqueries\n- Alias every table with a meaningful short name\n- Never SELECT *\n- Handle NULLs explicitly\n- Add a comment above each CTE explaining its job\n- If the question is ambiguous, list the assumptions first\n\nSCHEMA:\n{{schema}}\n\nQUESTION: {{question}}',
    category: 'SQL',
    tags: ['nl2sql', 'analytics'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 11,
    usageCount: 25,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'p-13',
    title: 'Design Critique Partner',
    description: 'Structured critique across hierarchy, rhythm and contrast.',
    content:
      'Critique the interface described below as a senior product designer.\n\nGo through, in order: visual hierarchy, spacing rhythm, typographic scale, colour contrast (give WCAG ratios), affordance clarity, empty/error states, and mobile reflow.\n\nFor each: what works, what breaks, and the smallest change with the biggest payoff.\nEnd with the 3 changes I should make first.\n\nSCREEN: {{description}}',
    category: 'Design',
    tags: ['critique', 'ui', 'a11y'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 12,
    usageCount: 19,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(12),
  },
  {
    id: 'p-14',
    title: 'Design System Token Namer',
    description: 'Semantic token names that survive a rebrand.',
    content:
      'Given the raw palette and type scale below, produce a semantic token set.\n\nRules:\n- Names describe role, not appearance (surface-raised, not gray-100)\n- Provide light and dark values for every token\n- Flag any pair failing WCAG AA with its contrast ratio\n- Output as CSS custom properties plus a short usage table\n\nPALETTE: {{palette}}',
    category: 'Design',
    tags: ['design-system', 'tokens'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 13,
    usageCount: 6,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'p-15',
    title: 'Thread Hook Machine',
    description: '10 opening lines engineered to stop the scroll.',
    content:
      'Write 10 opening lines for a thread about: {{topic}}\n\nUse a different mechanism per line: contrarian, numbers, personal loss, curiosity gap, before/after, insider secret, myth-bust, timeline, question, blunt statement.\n\nEach under 18 words. No emojis. No "Let that sink in." Rank them by expected stop-rate and explain the top pick in one line.',
    category: 'Social Media',
    tags: ['hooks', 'twitter', 'growth'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 14,
    usageCount: 48,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: 'p-16',
    title: 'Monthly Content Calendar',
    description: '4-week posting plan balanced across content pillars.',
    content:
      'Build a 4-week content calendar for {{brand}} on {{platform}}.\n\nBalance across pillars: educate (40%), prove (25%), opinion (20%), behind-the-scenes (15%).\n\nFor each post give: date, pillar, hook, format, CTA, and the asset needed.\nEnd with 3 repurposing chains (one post → three derivatives).',
    category: 'Social Media',
    tags: ['calendar', 'planning'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 15,
    usageCount: 13,
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },
  {
    id: 'p-17',
    title: 'Weekly Review Facilitator',
    description: 'Guides a sharp 20-minute weekly retrospective.',
    content:
      'Run my weekly review. Ask these one at a time and wait for my answer:\n1. What actually moved the needle this week?\n2. What consumed time but produced nothing?\n3. What did I avoid, and what is the real reason?\n4. What is the one thing that makes next week easier?\n\nThen output: 3 priorities for next week, 2 things to delete, and 1 thing to delegate. Be direct about patterns you notice.',
    category: 'Productivity',
    tags: ['review', 'planning', 'weekly'],
    isFavorite: true,
    isPinned: true,
    displayOrder: 16,
    usageCount: 71,
    createdAt: daysAgo(23),
    updatedAt: daysAgo(1),
  },
  {
    id: 'p-18',
    title: 'Meeting Notes → Decisions',
    description: 'Extracts decisions, owners and open questions only.',
    content:
      'Compress the transcript below into:\n\nDECISIONS — what was actually decided (not discussed)\nACTIONS — owner, task, due date (mark [NO OWNER] when unassigned)\nOPEN QUESTIONS — unresolved, with who must answer\nRISKS — anything raised and dropped\n\nDiscard pleasantries and repetition. If nothing was decided, say so plainly.\n\nTRANSCRIPT:\n{{transcript}}',
    category: 'Productivity',
    tags: ['meetings', 'summary', 'notes'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 17,
    usageCount: 39,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: 'p-19',
    title: 'Rubber Duck Explainer',
    description: 'Explains anything at three depths in one pass.',
    content:
      'Explain {{concept}} three times:\n1. To a curious 12-year-old, using one analogy\n2. To a competent generalist, with the mechanism\n3. To an expert, including the caveats and where the analogy breaks\n\nThen list the 3 misconceptions people most often hold about it.',
    category: 'Others',
    tags: ['learning', 'explain'],
    isFavorite: false,
    isPinned: false,
    displayOrder: 18,
    usageCount: 30,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  {
    id: 'p-20',
    title: 'Decision Pre-Mortem',
    description: 'Imagines the failure before you commit to the plan.',
    content:
      'It is 12 months from now and the decision below failed badly.\n\nWrite the post-mortem: the top 6 causes ranked by likelihood, the earliest warning signal for each, and the cheapest safeguard we could put in place today.\n\nThen state whether the decision is still worth making, and what would change your mind.\n\nDECISION: {{decision}}',
    category: 'Others',
    tags: ['decisions', 'risk', 'strategy'],
    isFavorite: true,
    isPinned: false,
    displayOrder: 19,
    usageCount: 8,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];
